sudo: required
language: generic 

services: 
    - docker
    
before_install:
    - docker build -t jconnro/Docker-React -f Dockerfile.dev .

script:
     - docker run -e CI=true JConnrO/Docker-React npm run test

      